from enum import Enum

class ChatIntent(str, Enum):
    DISCOVER_FACILITIES = "DISCOVER_FACILITIES"
    DISCOVER_SLOTS = "DISCOVER_SLOTS"
    CHECK_AVAILABILITY = "CHECK_AVAILABILITY"
    SELECT_SLOT = "SELECT_SLOT"
    CONFIRM_BOOKING = "CONFIRM_BOOKING"
    RESET = "RESET"
    UNKNOWN = "UNKNOWN"
